name: CI
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 7 * * *'  # 8AM CET/11PM PT

jobs:
  set-nightly:
    # don't schedule nightlies on forks
    if: github.event_name == 'schedule' && github.repository == 'leanprover/lean4'
    runs-on: ubuntu-latest
    outputs:
      nightly: ${{ steps.set.outputs.nightly }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Nightly
        id: set
        run: |
          if [[ -n '${{ secrets.PUSH_NIGHTLY_TOKEN }}' ]]; then
            git remote add nightly https://foo:'${{ secrets.PUSH_NIGHTLY_TOKEN }}'@github.com/${{ github.repository_owner }}/lean4-nightly.git
            git fetch nightly --tags
            LEAN_VERSION_STRING="nightly-$(date -u +%F)"
            # do nothing if commit already has a different tag
            if [[ $(git name-rev --name-only --tags --no-undefined HEAD 2> /dev/null || echo $LEAN_VERSION_STRING) == $LEAN_VERSION_STRING ]]; then
              echo "::set-output name=nightly::$LEAN_VERSION_STRING"
            fi
          fi

  build:
    needs: set-nightly
    if: always()
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell || 'bash -euxo pipefail {0}' }}
    strategy:
      matrix:
        include:
          # portable release build: use channel with older glibc (2.27)
          - name: Linux
            os: ubuntu-latest
            check-stage3: true
            test-speedcenter: true
          - name: Linux Debug
            os: ubuntu-latest
            CMAKE_OPTIONS: -DCMAKE_BUILD_TYPE=Debug
          - name: Linux fsanitize
            os: ubuntu-latest
            # turn off custom allocator & symbolic functions to make LSAN do its magic
            CMAKE_OPTIONS: -DLEAN_EXTRA_CXX_FLAGS=-fsanitize=address,undefined -DLEANC_EXTRA_FLAGS='-fsanitize=address,undefined -fsanitize-link-c++-runtime' -DSMALL_ALLOCATOR=OFF -DBSYMBOLIC=OFF
            # exclude problematic tests
            CTEST_OPTIONS: -E laketest
          - name: macOS
            os: macos-latest
            release: true
            shell: bash -euxo pipefail {0}
            CMAKE_OPTIONS: -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15
            llvm-url: https://github.com/leanprover/lean-llvm/releases/download/13.0.0/lean-llvm-x86_64-apple-darwin.tar.zst
            prepare-llvm: script/prepare-llvm-macos.sh lean-llvm*
            binary-check: otool -L
      # complete all jobs
      fail-fast: false
    name: ${{ matrix.name }}
    env:
      # must be inside workspace
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPRESS: true
      # current cache limit
      CCACHE_MAXSIZE: 200M
      # squelch error message about missing nixpkgs channel
      NIX_BUILD_SHELL: bash
      LSAN_OPTIONS: max_leaks=10
      # somehow MinGW clang64 (or cmake?) defaults to `g++` even though it doesn't exist
      CXX: c++
    steps:
      - name: Pack
        run: |
          mkdir pack
          touch pack/pock
      - uses: actions/upload-artifact@v2
        if: matrix.release
        with:
          name: build-${{ matrix.name }}
          path: pack/*

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Release
        uses: softprops/action-gh-release@v1       
        with:
          files: artifacts/*/*
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  release-nightly:
    needs: [set-nightly, build]
    if: needs.set-nightly.outputs.nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # needed for tagging
          fetch-depth: 0
          token: ${{ secrets.PUSH_NIGHTLY_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Prepare Nightly Release
        run: |
          git remote add nightly https://foo:'${{ secrets.PUSH_NIGHTLY_TOKEN }}'@github.com/${{ github.repository_owner }}/lean4-nightly.git
          git fetch nightly --tags
          git tag ${{ needs.set-nightly.outputs.nightly }}
          git push nightly ${{ needs.set-nightly.outputs.nightly }}
          last_tag=$(git describe HEAD^ --abbrev=0 --tags)
          echo -e "*Changes since ${last_tag}:*\n\n" > diff.md
          git show $last_tag:RELEASES.md > old.md
          #./script/diff_changelogs.py old.md doc/changes.md >> diff.md
          diff --changed-group-format='%>' --unchanged-group-format='' old.md RELEASES.md >> diff.md || true
          echo -e "\n*Full commit log*\n" >> diff.md
          git log --oneline $last_tag..HEAD | sed 's/^/* /' >> diff.md
      - name: Release Nightly
        uses: softprops/action-gh-release@v1
        with:
          body_path: diff.md
          prerelease: true
          files: artifacts/*/*
          fail_on_unmatched_files: true
          tag_name: ${{ needs.set-nightly.outputs.nightly }}
          repository: ${{ github.repository_owner }}/lean4-nightly
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_NIGHTLY_TOKEN }}
