name: Nix CI
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: nix --experimental-features "nix-command flakes" shell .#nix -c bash -euo pipefail {0}
    strategy:
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            nix_url: https://hydra.nixos.org/build/130670999/download/1/nix-2.4pre20201117_ae31916-x86_64-linux.tar.xz
          - name: macOS
            os: macos-latest
            nix_url: https://hydra.nixos.org/build/130670982/download/1/nix-2.4pre20201117_ae31916-x86_64-darwin.tar.xz
      # complete all jobs
      fail-fast: false
    env:
      CACHIX_AUTH_TOKEN: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install flakes-enabled Nix manually from Hydra since `install-nix-action` doesn't accept raw tarballs
      - name: Install Nix
        shell: bash -euo pipefail {0}
        run: |
          curl ${{ matrix.nix_url }} | tar -xJ
          nix-*/install --daemon --daemon-user-count 4 --no-channel-add --darwin-use-unencrypted-nix-store-volume
          rm -rf nix-*
      # Call `install-nix-action` anyways to run its Actions-specific setup
      - name: Setup Nix
        uses: cachix/install-nix-action@v12
      - name: Further setup Nix
        run: |
          echo '
            max-jobs = auto
            extra-sandbox-paths = /nix/var/cache/ccache
            extra-trusted-substituters = https://lean4.cachix.org/
            extra-trusted-public-keys = lean4.cachix.org-1:mawtxSxcaiWE24xCXXgh3qnvlTkyU7evRRnGeAhD4Wk=' | sudo tee /etc/nix/nix.conf
          sudo mkdir -m0770 -p /nix/var/cache/ccache
          sudo chown root:nixbld /nix/var/cache/ccache
          sudo pkill nix-daemon  # reload

          # install & use Cachix manually since `cachix-action` pushes *all* derivations (incl. `$mod-deps`, stage 2&3, etc.)
          nix-env -iA cachix -f https://cachix.org/api/v1/install
      - name: Setup CCache Cache
        uses: actions/cache@v2
        with:
          path: /nix/var/cache/ccache
          key: ${{ matrix.name }}-nix-ccache-${{ github.sha }}
          # fall back to (latest) previous cache
          restore-keys: |
            ${{ matrix.name }}-nix-ccache
      - name: Build
        run: |
          nix build -v --print-build-logs .#stage0
          cachix push -j4 lean4 ./result
          nix build -v --print-build-logs
          cachix push -j4 lean4 ./result
      - name: Test
        run: |
          nix build -v --print-build-logs .#test
          cachix push -j4 lean4 ./result
      - name: CCache stats
        run: ccache -s
