name: Wasm Test
on: [push]
jobs:
  wasm-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install CCache
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.44
          actions-cache-folder: 'emsdk'
      - name: Install 32bit c libs
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib
      - name: Compile wasm
        run: |
          cd ${{ github.workspace }}/build/release
          cmake ../.. -DCMAKE_C_COMPILER_WORKS=1 -DSTAGE0_USE_GMP=OFF -DSTAGE0_LEAN_EXTRA_CXX_FLAGS='-m32' -DSTAGE0_LEANC_OPTS='-m32' -DSTAGE0_CMAKE_CXX_COMPILER=clang++ -DSTAGE0_CMAKE_C_COMPILER=clang -DUSE_GMP=OFF -DMMAP=OFF -DSTAGE0_MMAP=OFF -DUSE_GMP=OFF -DCMAKE_AR=${{ github.workspace }}/emsdk/emsdk-main/upstream/emscripten/emar -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/emsdk/emsdk-main/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
          make -j4
      - name: Test wasm binary
        run: |
          cd ${{ github.workspace }}/build/release
          echo "#check Nat" | LEAN_PATH=${{ github.workspace }}/build/release/stage1/bin node --stack-size=8192 stage1/bin/lean --stdin

